### ISSUE TITLE
Empty repository

### ISSUE THREAD

**Issue by davidromani** [enricostano/aplicoop#1]
Hola Enrico!

Que tal? Como va todo? Nos conocimos hace unos años en un evento de Som Energia en Calafell, te acuerdas?

Ahora tengo que instalar Aplicoop para mi grupo de consumo y me gustaria (si es posible) tener el código fuente aquí en GitHub. De esta manera os puedo ayudar un poco con algun pull request más fácil que con SourceForge (creo).

Un saludo y muchas gracias.

**Comment by davidromani** [comment]
@enricostano has recibido el mensaje?

**Comment by enricostano** [comment]
hola @davidromani 

que tal? claro que me acuerdo! Ya no estoy colaborando en el proyecto Aplicoop, ahora estamos trabajando en un proyecto SaaS que se llama [Katuma](http://www.katuma.org). Se trata de ofrecer un servicio en linea para los grupos de compra. Esta' desarrollado en Ruby (Rails) y Javascript (Backbone/Marionette) y estamos trabajando en la beta privada que espero salga dentro de un par de meses.

Estaria bien si pudieras participar en el proyecto, con desarrollo, beta testing o lo que sea :smiley: 

Los repositorio en los cuales estamos trabajando son los siguientes:
- Backend: https://github.com/coopdevs/katuma
- Frontend: https://github.com/coopdevs/katuma-web-app

Para cualquier duda o pregunta aqui estoy! Puedes abrir issues en esos repos tambien.

Un abrazo y hasta pronto!

**Comment by davidromani** [comment]
Ok, me lo miro y te digo algo, tiene muy buena pinta!

Entonces si no lo he entenido mal, katuma seria la evolución de apicoop? La puedo usar como herramienta para nuestro grupo de consumo?

**Comment by enricostano** [comment]
Decimos que Katuma quiere enfocar el pr

**Comment by enricostano** [comment]
Decimos que Aplicoop se enfoca a un solo grupo de consumo mientras que Katuma quiere resolver mas problemas como por ejemplo:
- eliminar esfuerzo de self-hosting
- eliminar el riesgo del tipico efecto "el que lo monto' se fue"
- juntar esfuerzos de desarrollo entre distintos grupos de compra
- compartir gastos de mantenimiento entre grupos de compra
- implicar los productores en el proceso de compras de grupo
- introducir tecnicas de desarrollo mas actuales usando frameworks, standards, etc

y mucho mas :smiley: 

Aplicoop sigue su camino, pero no tengo muchas mas informaciones.

Sobre lo de usar Katuma para tu grupo de compra lo que podemos hacer de momento es apuntaros a la beta privada para darnos un primer feedback y, por supuesto, participar en el proyecto de cualquier forma:
- desarrollo software
- ayuda en la parte de sistemas (deploy en VPS, etc)
- traducciones
- comunicacion

De momento somos 4 personas, todos desarrolladores y necesitamos mas gente!

Seguimos hablando y gracias!

**Comment by davidromani** [comment]
Ok, de Rails y Backbone no he tocado nada pero con el tema de las traducciones seguro que puedo hechar una mano. Yo tengo más experiencia en Symfony, Bootstrap y AngularJS por si os vale :-)

Me parece muy buena idea que exista una APIRest para separar server-side y client-side.

También me registré en el newsletter para recibir un aviso sobre la beta privada, me interesa probarla. :+1:

**Comment by enricostano** [comment]
Perfecto @davidromani ! Quedamos en contacto y nos vemos en la presentacion de la beta privada o incluso antes :smiley:
